---
name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test 1.20 since that's the earliest version we support.
        go-version: ['1.20', '1.23', '1.24']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v -shuffle=on -race ./...
      - name: Test Coverage
        run: go test -v -shuffle=on -covermode=atomic ./...
      - name: Vet
        run: go vet
